import Head from "next/head";
import Button from "../components/Button";
import Hero from "../layouts/Hero";
import Statictics from "../layouts/Statictics";

export default function Home() {
  return (
    <div>
      <Head>
        <title>URL shortener | FEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="pb-40 md:pt-24 md:pb-52">
        <Hero />
      </section>
      <section className="bg-gray-200 md:pb-36">
        <Statictics />
      </section>

      <section className="flex items-center justify-center py-20 text-center bg-primaryDark">
        <div>
          <h4 className="mb-4 text-xl font-bold text-white md:text-4xl md:mb-8">
            Boose your links today
          </h4>
          <div className="md:hidden">
            <Button rounded>
              <span className="text-lg">Get Started</span>
            </Button>
          </div>

          <div className="hidden md:block">
            <Button rounded large>
              <span className="text-lg">Get Started</span>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
